export { default as DialogLogin } from './DialogLogin'
export { default as DialogLoginSms } from './DialogLoginSms'
export { default as DialogPassChange } from './DialogPassChange'
export { default as DialogRegedit } from './DialogRegedit'
export { default as DialogOrder } from './DialogOrder'
export { default as DialogBuy } from './DialogBuy'
export { default as DialogHardsn } from './DialogHardsn'
export { default as DialogAbout } from './DialogAbout'
export { default as DialogTest } from './DialogTest'

